### ISSUE TITLE
打包成exe后运行出错

### ISSUE THREAD

**Issue by ysc703** [daltonxiong/TextLabelTool#1]
您好，按照您的步骤生成了exe，但是运行报错“Failed to execute script main”。
目前没什么思路解决，麻烦帮忙看一下。
非常感谢^_^

**Comment by daltonxiong** [comment]
打包成单个文件会在某些电脑上报错

那你试下打包命令去掉 --onefile  参数

**Comment by ysc703** [comment]
问题还是如此，又仔细看了下打包过程的信息，有一个异常No module named 'Crypto.Math'。baidu、Google都没看有什么解决方法。
请问由打包好的吗？

**Comment by daltonxiong** [comment]
我这边是在ubuntu上装了个32位的win7虚拟机进行打包的 估计打包出来你也跑不了, 如果你需要的话可以邮箱发你

你再试一下去掉两个参数  --onefile 和 --windowed

**Comment by ysc703** [comment]
还是不行哈^_^
我有时间再研究研究，估计还是Crypto.Math的问题。
多谢啦
